### ISSUE TITLE
Enhance `version` command output

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#123]
Currently the version only prints the commit info.
Would be easier for future bug reports to also print the golang version used and the system it was built for.
Example:
```
Semantic version: v0.1.2
Commit: xxxxxxxxxxxxxxxxxxxxxxxxxxx
Build Date: <some date>
System version: amd64/linux
Golang version: go1.19.1
```

**Comment by mtsitrin** [comment]
we're using the default `github.com/cosmos/cosmos-sdk/version` command

It prints `version` by default and has `--long` to print all additional data

**Comment by omritoptix** [comment]
ok perfect. closing this.
