### ISSUE TITLE
Run rollapp with external token as native token

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#124]
Run a rollapp where the native token is an IBC denom.

The rollapp shouldn't be allowed to mint this token

**Comment by shaolin-flow** [comment]
To maintain a good UX my suggestion for the 35-C testnet:

- Allocate native tokens on genesis
- Allow for mint to delegators
- Allow for native denom and IBC/path for gas

However, in a production environment the RollApp with foreign denom should have:

- No native tokens minted on genesis
- No perpetual mint 

The purpose of having a foreign token as a gas fee is:

- *Should* reduce any regulatory reqs. for maintaining a blockchain application (the deployer isn't selling a security/currency). Thus, it cannot mint the tokens on genesis.
- Reduce mental overhead for creating a utility for the token. Developers are not economists and shouldn't be.
- Removal of BFT security assumptions on the execution layer reduces the necessity to perpetually fund validators for block production. Gas needs to be greater than base layer costs, which can be estimated in MVP.

**Comment by mtsitrin** [comment]
For EVM rollapp, the Eth transactions supports single denom for fees

Thats the reason that if we want to use IBC for fees, it needs to be the 'native' denom
As it's IBC, it bad idea to have some minting on the rollapp
