### ISSUE TITLE
Querying validators at height returns error though no pruning occured

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#141]
steps to reproduce on rollappX:

`rollappd q staking validators --height 11803406`

`Error: rpc error: code = InvalidArgument desc = failed to load state at height 11803406; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 12206715): invalid request`

**Comment by anhductn2001** [comment]
We close it because we can't reproduce err
