### ISSUE TITLE
Ensure Idempotency for `roller config init`

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#178]
Currently, certain scripts such as `setup_ibc.sh` used for bootstrapping a Rollapp do not offer predictable results when rerun with varying environment variables, necessitating manual adjustments to work correctly after the first execution. Specifically, the 'roller config init' command should be made idempotent, ensuring its results are consistent and predictable upon re-execution, irrespective of environment variable changes.

**Comment by mtsitrin** [comment]
dup of https://github.com/dymensionxyz/roller/issues/30
