### ISSUE TITLE
setup ibc script redundant commands

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#179]
Currently the `setup_ibc` script checks the balances of the relayer by assuming settlement executable (i.e dymd) and rollapp executable (e.g rollappd) exists on the machine. 
This can be done using the `rly query balances` command.

**Comment by mtsitrin** [comment]
This script will be moved to the rollapp template repo

Unless we want to remove the `register` and `setup_ibc` and reference to `roller` instead
