### ISSUE TITLE
seperate the rollapp `app` from the RDK

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#189]
Currently in order to add custom logic to the RDK it needs to be forked and changed in-place.

For the RDK to be more of a framework regarding its useability, we should:

- [ ] move the `app` to a separate repo
 - functioning as a rollapp template
 - reusing the modules and dymint commands from the RDK
- [ ] move `dymint` commands to a `server` package

**Comment by mtsitrin** [comment]
@omritoptix what u say about using https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template for the rollapp?

Move all core logic to the RDK, and create `rollapp` template repo

**Comment by shaolin-flow** [comment]
Should use this [template](https://github.com/julienrbrt/chain-minimal) with this commit b1519c6ece387d350a92949586daad4246396085 with SDK 46 support for the RollApp `simapp` template.

**Comment by mtsitrin** [comment]
@shaolin-flow 
I will base our rollappd on it
But it will be different

few open issues
Do we want the `gov` inside?
`IBC`?

we also have epochs and epoch based minting
