### ISSUE TITLE
Mint module should return `DeveloperRewardsReceiver` params option

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension-rdk#233]
### Overview

Original Osmosis `mint` module includes a `DeveloperRewardsReceiver`. This was removed when forking the module. However, it seems reasonable to assume a RollApp mints to both the Sequencer and core developers. This is particularly relevant in situations where the Sequencer and core developers are two separate economic entities.

### Suggestion

Return `DeveloperRewardsReceiver` to the mint module params.

**Comment by mtsitrin** [comment]
@shaolin-flow I disagree here
I think it's very opinionated. we forked the evmos repo **for easy to use evm rollapp template**

Every chain doing it's incentivises differtently
any specific use-case enhancement, shouldn't be part of the framework itself

**Comment by mtsitrin** [comment]
anyway this issue should be transferred to the Evmos fork repo

**Comment by shaolin-flow** [comment]
Closing
