### ISSUE TITLE
Remove dependency in `dymensionxyz/rollapp` package

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#278]
This creates circular dependency and leads to unexpected issues where tests are failing as they depend on this package (e.g when trying to update the ibc package)

**Comment by mtsitrin** [comment]
I'll return the rollapp app code back here from the rollapp repo

**Comment by mtsitrin** [comment]
as discussed, the alternative of copying the `app` to this repo is worse

the `rollapp` repo referenced by the RDK is for UnitTesting purposes, and should be considered accordingly when upgrading
