### ISSUE TITLE
Inconsistent context height usage

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#362]
In evmos:x/evm/keeper/grpc_query.go:407, the contextHeight variable is
defined to coincide with the requested block number. However,
rpc/backend/tracing.go:116 and 173 defines contextHeight as the one block
before the requested height (i.e., height - 1).
This inconsistency could result in difficulty when debugging Ethereum transactions.

**Comment by mtsitrin** [comment]
@omritoptix we upstreamed this as bug fix from recent evmos in https://github.com/dymensionxyz/evmos/pull/18

**Comment by mtsitrin** [comment]
@VictorTrustyDev 
Regarding the fix u did on `x/evm/keeper/grpc_query.go:407` , 
do we need to fix it in `rpc/backend/tracing.go` as well?

**Comment by VictorTrustyDev** [comment]
@mtsitrin no, that's enough
