### ISSUE TITLE
feat: use operator address as the permissioned address

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#368]
currently, both `x/denommetada` and `x/hub-genesis` have allow list in their params.

we should get this data from the active sequencer (i.e the sequncer is the permissioned address)
to allow better usability, we can have for the sequencer list of "permissioned addresses" to grant permissions as well

**Comment by omritoptix** [comment]
I think it's not ideal for 2 reasons:
1. the usage of multi-sig may be wanted for this
2. the attack surface increases

Either way the x/hub-genesis "permissioend address" is a temporary solution until we will use IBC for validation the genesis event so don't think it's worth the effort.

**Comment by omritoptix** [comment]
closing this as for next stage we're gonna use ibc validation for that
