### ISSUE TITLE
bech32 prefix not read when validating genesis

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#405]
```
rollapp-evm validate-genesis ~/Downloads/finalGenesis.json                                                                                       
Error: error validating genesis file /Users/mtsitrin/Downloads/finalGenesis.json: invalid Bech32 prefix; expected rol, got nim
```

**Comment by Kwaskoff** [comment]
@mtsitrin mtsitrin where did u get this genesis

**Comment by mtsitrin** [comment]
It was candidate for testnet rollapp
but should be easy to reproduce:
* init genesis with prefix: "test" and move it to `~/testGensis.json`
* init genesis again with prefix: "rol" (set by default on `~/.rollapp_evm/config/genesis.json`)
* run `rollapp-evm validate-genesis ~/testGensis.json`

**Comment by omritoptix** [comment]
clsoing as not relevant as moved away from this method
