### ISSUE TITLE
Genesis bridge: optimize sending denom metadata RA->Hub when there are many genesis accounts

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension-rdk#456]
Each genesis transfer includes the denom metadata, which might be costly for e.g. airdrops

**Comment by danwt** [comment]
see also https://github.com/dymensionxyz/dymension-rdk/issues/454

**Comment by danwt** [comment]
Cant easily be done because of out-of-order AFAIU
Maybe @zale144 you have an idea? Something to integrate with your work?

**Comment by danwt** [comment]
@mtsitrin is it possible to close this with the genesis bridge rework?

**Comment by mtsitrin** [comment]
yes, it's been refactored. denom metadata sent once regardless of the genesis accounts
