### ISSUE TITLE
Genesis bridge: better UX for chains without genesis transfers

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension-rdk#457]
see https://github.com/dymensionxyz/dymension/issues/922

**Comment by mtsitrin** [comment]
@danwt we plan to add
`disable transfers on the rollapp until successful acks have been received`
on top of this PR?

also, I think some validation on the genesis tokens should be implemented
(as mentioned in https://github.com/dymensionxyz/dymension-rdk/pull/449 comments)

**Comment by danwt** [comment]
done ^
