### ISSUE TITLE
Add debug syncing commands for dymint

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#481]
The following cli command should reveal:

- [ ] height of last block received from p2p
- [ ] height of last block received from da
- [ ] last block applied source (da or gossip)
- [ ] number of accumulated blocks pending to be applied (cache occupancy)
- [ ] height of lowest block pending in cache
- [ ] height of highest received block

**Comment by zale144** [comment]
closing in favor of https://github.com/dymensionxyz/dymint/issues/978
