### ISSUE TITLE
Run e2e with Ethermint

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension-rdk#5]
# Overview

We need to be able to test all functionalities e2e with Ethermint for testnet. Test that all functionalities of a standard Cosmos SDK chain works with Ethermint RollApp.

**Comment by mtsitrin** [comment]
- [ ] add evm module to the rdk
- [ ] compilation target to create EVM enabled rollapp
- [ ] Test EVM smart contracts
