### ISSUE TITLE
Remove the need to supply proposer reward address on genesis

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#509]
As rollapp operators won't necessarily know the relevant sequencer reward address ,on start we need to remove this requirement. 

```
// InitGenesis initializes the sequencers module's state from a provided genesis state.
// We return the for ValidatorUpdate only the sequencers set by dymint
func (k *Keeper) InitGenesis(ctx sdk.Context, genState types.GenesisState) []abci.ValidatorUpdate {
	var updates []abci.ValidatorUpdate
	k.SetParams(ctx, genState.Params)

	operatorAddr, err := sdk.ValAddressFromBech32(genState.GenesisOperatorAddress)
	if err != nil {
		panic(err)
	}
```

This can be provided later using the [create sequencer tx](https://github.com/dymensionxyz/dymension-rdk/issues/508)

**Comment by danwt** [comment]
https://github.com/dymensionxyz/dymension-rdk/blob/2a1f308c31141143c20fadee37578c5be0df4f87/x/sequencers/keeper/genesis.go#L10-L56
