### ISSUE TITLE
no error event is emitted/logged in case of ibc err ack

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension-rdk#532]
In case an error ack is returned, the error should be emitted as event for debug purposes. 
currently there is no error emitted which makes it hard to understand the root cause.

**Comment by danwt** [comment]
there is already an event right

https://github.com/cosmos/ibc-go/blob/893b7afd6e924a347866336918e37d880d67b0fc/modules/core/04-channel/keeper/events.go#L179-L205

**Comment by danwt** [comment]
https://github.com/cosmos/ibc-go/blob/6fbc8c926706969ee3dd47950014a0d65348fb3f/modules/core/04-channel/keeper/packet.go#L356

**Comment by zale144** [comment]
@danwt yea, but where the err at

**Comment by danwt** [comment]
but it's written right here https://github.com/cosmos/ibc-go/blob/893b7afd6e924a347866336918e37d880d67b0fc/modules/core/04-channel/keeper/events.go#L193
in the bytes

**Comment by zale144** [comment]
I know that, I'm talking about the actual ’err‘ that is the root cause, not the obfuscated generic message with abci code
