### ISSUE TITLE
Rollapp should enforce Hub->Rollapp connection establishment

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#580]
As we validate `genesis bridge` on `OnChanOpenConfirm`
we need to make sure that IBC channel cannot be established the other way around 

(https://github.com/dymensionxyz/e2e-tests/issues/258)

**Comment by mtsitrin** [comment]
seems it's already blocked in `AnteHandler`
```
cosmosante.NewRejectMessagesDecorator(
	[]string{
		sdk.MsgTypeURL(&conntypes.MsgConnectionOpenInit{}), // don't let any connection open from the Rollapp side (it's still possible from the other side)
	},
),
```

**Comment by omritoptix** [comment]
@mtsitrin closing this than.

**Comment by mtsitrin** [comment]
I think @anhductn2001 said it's not working on latest version

@anhductn2001 can u attach logs?

**Comment by anhductn2001** [comment]
We can close it!
