### ISSUE TITLE
error when creating new ibc client to revive expired client

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymension-rdk#610]
result when running `rollapp-evm tx ibc client create ./^Cient_state.json ./consensus_state.json --from rol-user --keyring-backend test --fees 2000000000000aedt`

`Nov 28 11:09:16 barcelona roller[20131]: time="Nov 28 11:09:16.371" level=error msg="ante handler panicked[error expected *legacytx.LegacyMsg when using amino JSON stack trace goroutine 3205 [running]:\nruntime/debug.Stack()\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/dymensionxyz/rollapp-evm/app/ante.Recover({0x439a320, 0xc0006b58a0}, 0xc0043ef628)\n\t/home/sergi/seal/tmpo/rollapp727734012/app/ante/ante.go:194 +0xfb\npanic({0x2fdeb80?, 0xc00226cd80?})\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/panic.go:785 +0x132\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/setup.go:57 +0x205\npanic({0x2fdeb80?, 0xc00226cd80?})\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/panic.go:785 +0x132\ngithub.com/cosmos/cosmos-sdk/x/auth/migrations/legacytx.StdSignBytes({0xc006e65bc0, 0x1a}, 0x0, 0x2540be401, 0x0, {{0xc0049cb590, 0x1, 0x1}, 0x30d40, {0x0, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/migrations/legacytx/stdsign.go:60 +0x453\ngithub.com/evmos/evmos/v12/ethereum/eip712.decodeProtobufSignDoc({0xc003fb5440, 0x239, 0x239})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/ethereum/eip712/encoding.go:196 +0x6da\ngithub.com/evmos/evmos/v12/ethereum/eip712.GetEIP712TypedDataForMsg({0xc003fb5440, 0x239, 0x239})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/ethereum/eip712/encoding.go:73 +0x251\ngithub.com/evmos/evmos/v12/ethereum/eip712.GetEIP712BytesForMsg({0xc003fb5440?, 0xfb45aab580804de4?, 0x16f144a2416e7b15?})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/ethereum/eip712/encoding.go:51 +0x58\ngithub.com/evmos/evmos/v12/crypto/ethsecp256k1.PubKey.verifySignatureAsEIP712({{0xc003fdd3e0?, 0xee805d?, 0xc002743500?}}, {0xc003fb5440, 0x239, 0x239}, {0xc003fbac80, 0x41, 0x41})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/crypto/ethsecp256k1/ethsecp256k1.go:235 +0x65\ngithub.com/evmos/evmos/v12/crypto/ethsecp256k1.PubKey.VerifySignature({{0xc003fdd3e0?, 0xc000000001?, 0x4372788?}}, {0xc003fb5440, 0x239, 0x239}, {0xc003fbac80, 0x41, 0x41})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/crypto/ethsecp256k1/ethsecp256k1.go:228 +0xaa\ngithub.com/cosmos/cosmos-sdk/x/auth/signing.VerifySignature({0x43b1cd8, 0xc0049cb548}, {{0xc002743500, 0x2a}, {0xc0047900a0, 0x1a}, 0x0, 0x2540be401, {0x43b1cd8, 0xc0049cb548}}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/signing/verify.go:21 +0x189\ngithub.com/dymensionxyz/rollapp-evm/app/ante.sigCheckDecorator.AnteHandle({{_, _}, {_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, ...}, ...}, ...)\n\t/home/sergi/seal/tmpo/rollapp727734012/app/ante/sigcheck_decorator.go:90 +0x97a\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SigGasConsumeDecorator.AnteHandle({{_, _}, _}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/sigverify.go:194 +0x577\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateSigCountDecorator.AnteHandle({{_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/sigverify.go:384 +0x3ae\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetPubKeyDecorator.AnteHandle({{_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/sigverify.go:126 +0xace\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/evmos/evmos/v12/app/ante/cosmos.DeductFeeDecorator.AnteHandle({{0x7fba780a1fd0, 0xc000e65b80}, {0x7fba780a2048, 0xc000782c60}, {0x4363980, 0xc000b45b00}, {0x0, 0x0}, {0x7fba780a2078, 0xc000bf2c60}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/app/ante/cosmos/fees.go:104 +0x377\ngithub.com/dymensionxyz/dymension-rdk/server/ante.BypassIBCFeeDecorator.AnteHandle({{0x4363740, 0xc00290e660}, {{{0x43712a8, 0xc0022cd580}, {0x43bae10, 0xc000d14220}, {{...}, 0xc000134a78, {...}, {...}, ...}, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymension-rdk@v1.6.1-0.20241119103059-def6322e4345/server/ante/bypass_ibc_fee_decorator.go:46 +0x355\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ConsumeTxSizeGasDecorator.AnteHandle({{_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/basic.go:142 +0x58f\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/dymensionxyz/rollapp-evm/app/ante.CreateAccountDecorator.AnteHandle({{_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, ...}, ...}, ...)\n\t/home/sergi/seal/tmpo/rollapp727734012/app/ante/create_account_decorator.go:68 +0x6f7\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/evmos/evmos/v12/app/ante/cosmos.MinGasPriceDecorator.AnteHandle({{_, _}, {_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/app/ante/cosmos/min_price.go:94 +0x637\ngithub.com/dymensionxyz/dymension-rdk/server/ante.BypassIBCFeeDecorator.AnteHandle({{0x43636e0, 0xc0042cd660}, {{{0x43712a8, 0xc0022cd580}, {0x43bae10, 0xc000d14220}, {{...}, 0xc000134a78, {...}, {...}, ...}, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymension-rdk@v1.6.1-0.20241119103059-def6322e4345/server/ante/bypass_ibc_fee_decorator.go:46 +0x355\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateMemoDecorator.AnteHandle({{_, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/basic.go:66 +0x2ce\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/dymensionxyz/rollapp-evm/app/ante.PermissionedURLsDecorator.AnteHandle({_, {_, _, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, ...}, ...}, ...)\n\t/home/sergi/seal/tmpo/rollapp727734012/app/ante/decorator_permissioned_urls.go:38 +0x297\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.TxTimeoutHeightDecorator.AnteHandle({}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/basic.go:205 +0x26e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ValidateBasicDecorator.AnteHandle({}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/basic.go:34 +0x14e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.RejectExtensionOptionsDecorator.AnteHandle({_}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/ext.go:52 +0x10e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/auth/ante/setup.go:62 +0x546\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/evmos/evmos/v12/app/ante/cosmos.AuthzLimiterDecorator.AnteHandle({{_, _, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/app/ante/cosmos/authz.go:48 +0x18e\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/evmos/evmos/v12/app/ante/cosmos.RejectMessagesDecorator.AnteHandle({{_, _, _}}, {{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/evmos/v12@v12.1.6-dymension-v0.4.2/app/ante/cosmos/reject_msgs.go:54 +0x197\ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/handler.go:40 +0x136\ngithub.com/dymensionxyz/rollapp-evm/app/ante.NewHandler.func1({{0x439a0f0, 0x6489a20}, {0x43bad30, 0xc00454e9c0}, {{0xb, 0x2}, {0xc0047900a0, 0x1a}, 0xd07, {0x510b3b7, ...}, ...}, ...}, ...)\n\t/home/sergi/seal/tmpo/rollapp727734012/app/ante/ante.go:182 +0x834\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000e5fa40, 0x0, {0xc000bf4a00, 0x260, 0x261})\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:694 +0x6d9\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).CheckTx(0xc000e5fa40, {{0xc000bf4a00?, 0x0?, 0x0?}, 0x87123055?})\n\t/home/sergi/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/baseapp/abci.go:244 +0x86\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync(0xc000c80720, {{0xc000bf4a00?, 0x7fba7851ccd0?, 0x10?}, 0x3ef8ff8?})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/cometbft@v0.34.29-0.20241104165035-feade34f8f89/abci/client/local_client.go:104 +0xf9\ngithub.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync(0xc0022260a0?, {{0xc000bf4a00?, 0x260?, 0x261?}, 0x0?})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/cometbft@v0.34.29-0.20241104165035-feade34f8f89/proxy/app_conn.go:126 +0x22\ngithub.com/dymensionxyz/dymint/mempool/v1.(*TxMempool).CheckTx(0xc0022260a0, {0xc000bf4a00, 0x260, 0x261}, 0xc00226c700, {0x2?, {0x0?, 0x3?}})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/mempool/v1/mempool.go:227 +0x99\ngithub.com/dymensionxyz/dymint/rpc/client.(*Client).BroadcastTxSync(0xc002245590, {0x439a910, 0xc003fb0410}, {0xc000bf4a00, 0x260, 0x261})\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/client/client.go:225 +0xe3\ngithub.com/dymensionxyz/dymint/rpc/json.(*service).BroadcastTxSync(0x3?, 0x4?, 0xc003d528a0?)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/json/service.go:270 +0x4a\nreflect.Value.call({0x30269c0?, 0xc002178460?, 0xc001efa630?}, {0x357f93e, 0x4}, {0xc003ef98e8, 0x2, 0x380?})\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/reflect/value.go:581 +0xca6\nreflect.Value.Call({0x30269c0?, 0xc002178460?, 0xc0049caf78?}, {0xc003ef98e8?, 0x99fb20?, 0xc0022582a0?})\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/reflect/value.go:365 +0xb9\ngithub.com/dymensionxyz/dymint/rpc/json.(*handler).serveJSONRPCforWS(0xc002245890, {0x4379920, 0xc003bcf180}, 0xc0038757c0, 0x0)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/json/handler.go:99 +0x49f\ngithub.com/dymensionxyz/dymint/rpc/json.(*handler).serveJSONRPC(...)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/json/handler.go:54\nnet/http.HandlerFunc.ServeHTTP(0xc0022582a0?, {0x4379920?, 0xc003bcf180?}, 0xc000743508?)\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:2220 +0x29\nnet/http.(*ServeMux).ServeHTTP(0xe0?, {0x4379920, 0xc003bcf180}, 0xc0038757c0)\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:2747 +0x1ca\ngithub.com/dymensionxyz/dymint/rpc/json.(*handler).ServeHTTP(0xc002252a80?, {0x4379920?, 0xc003bcf180?}, 0xc0038757c0?)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/json/handler.go:49 +0x25\ngithub.com/dymensionxyz/dymint/rpc.(*Server).startRPC.(*Cors).Handler.func2({0x4379920, 0xc003bcf180}, 0xc0038757c0)\n\t/home/sergi/go/pkg/mod/github.com/rs/cors@v1.9.0/cors.go:236 +0x184\nnet/http.HandlerFunc.ServeHTTP(0x6452380?, {0x4379920?, 0xc003bcf180?}, 0xc00226c660?)\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:2220 +0x29\ngithub.com/dymensionxyz/dymint/rpc/middleware.Status.Handler.func1.1({0x4379920, 0xc003bcf180}, 0xc0038757c0)\n\t/home/sergi/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20241119162335-82f60adeb0cc/rpc/middleware/status.go:35 +0x191\nnet/http.HandlerFunc.ServeHTTP(0x414505?, {0x4379920?, 0xc003bcf180?}, 0xc003bcf101?)\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:2220 +0x29\nnet/http.serverHandler.ServeHTTP({0x4371a78?}, {0x4379920?, 0xc003bcf180?}, 0x6?)\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:3210 +0x8e\nnet/http.(*conn).serve(0xc0037a0990, {0x439a8d8, 0xc002111740})\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:2092 +0x5d0\ncreated by net/http.(*Server).Serve in goroutine 246\n\t/home/sergi/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/net/http/server.go:3360 +0x485\n]"`

**Comment by zale144** [comment]
passing the chain-id seems to make it work
